### ISSUE TITLE
Let `subpar` package handle subfigures (until they are natively support)

### ISSUE THREAD

**Issue by JamesxX** [maucejo/elsearticle#3]
https://github.com/maucejo/elsearticle/blob/bd90396f1123410352107ef72b3507c5d358fe0c/src/elsearticle.typ#L39-L44

The `subpar` package deals with many of the edge-cases that we'd otherwise need to deal with ourselves

**Comment by maucejo** [comment]
Actually, I have already thought to use the `subpar`. However, it doesn't seem to allow separate supplements : one for the caption and one for renferencing element. It is a common usage in my field to have caption with "Figure 1: ..." and cite it as "Fig. 1" in the texte (Ihave checked that in the guides of authors). That is why, I have implemented `subfigure` this way.

**Comment by maucejo** [comment]
The new release supports `subpar` now ;)
