### ISSUE TITLE
Breaks coauthor name in two

### ISSUE THREAD

**Issue by CGMossa** [maucejo/elsearticle#5]
I believe that I have one too many authors on a paper, and it broke "hyphenated" one of the names. Is it possible to patch that please?

**Comment by maucejo** [comment]
Can you post a screenshot ? I am not sure to properly understand what you exactly mean by "break".

**Comment by CGMossa** [comment]
Yes!
![image](https://github.com/user-attachments/assets/08910cbf-566e-4447-9dc3-dc4376b5328e)

I also just tried to insert `text(hyphenate:false)` everywhere where auth.name is present, and it still breaks up the name .

**Comment by maucejo** [comment]
Thanks, I will see if I can find a solution. But do you know if the latex class behaves the same ?

**Comment by CGMossa** [comment]
I don't know, no, but that didn't happen when I used the latex counterpart... And I had many names there too.

**Comment by CGMossa** [comment]
I still have the same behavior. I copied the new file to my project, and it still broken up.

**Comment by maucejo** [comment]
It is strange, because it seems to work - see https://typst.app/project/pglkb_3ZRppectMMKQWIBa
